### ISSUE TITLE
Não corre em Linux (CentOS 7 ou Ubuntu 20)

### ISSUE THREAD

**Issue by sqdv** [joaquimrcarvalho/timelink#1]
Installei o Docker Engine em Ubuntu 20.04.1 e em CentOS 7 (core). Em ambos os sistemas, a instalação do Docker finaliza sem erros e o programa funciona correctamente (sem sudo).

A instalação do MHK-Manager finaliza sem erros.

Contudo, mesmo após um reboot do sistema, o comando "mhk --help" ou "mhk start" retorna:

a) em CentOS:

bash: mhk: command not found...

O ficheiro .bash_profile_mhk contém:                                  

```
# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
# User specific environment and startup programs
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

```
b) em Ubuntu:

Command 'mhk' not found, did you mean:

(alternativas do repositório)

O ficheiro .bash_profile_mhk está vazio, com 0 bytes.

**Comment by Timelink-project** [comment]
Olá

Desculpas por ter visto isto tão tarde.

Nós temos uma versão a correr em CentOS, de modo que a resposta é sim.

O facto de bash_profile_mhk estar vazio indica que a instalação do Timelink não terminou corretamente.

Pedia que tentasse com o instalador mais recente. Se o problema persistir podemos trocar mensagens diretas para encontrar o problema.
